cart/urls.py
from django.urls import path

app_name = 'shopping_cart'

from.views import (
add_to_cart,
delete_from_cart,
order_details,
checkout,
process_payment,
update_transaction_records,
success,
)

urlpatterns = [
    path('add-to-cart/<int:id>/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name="purchase_success"),
    path('item/delete/<int:id>/', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name="checkout"),
    path('payment/<int:order_id>/', process_payment, name="process_payment"),
    path('update-transaction/<int:order_id>/', update_transaction_records, name="update_records"),

]

lol_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views


urlpatterns = [
    path('admin/', admin.site.urls),

    # shop app
    path('', views.product_list_view, name='home_page'), # home page

    path('product/', include('shop.urls')),

    path('about/', views.about_view, name='about_view'),

    path('contact/', views.contact_view, name='contact_view'),

    # users app
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),

    # cart app
    path('shopping-cart/', include('cart.urls')),
]

cart/models.py
from django.db import models

# Create your models here.
from users.models import CustomUser
from shop.models import Product


class OrderItem(models.Model):
    product = models.OneToOneField(Product, on_delete=models.CASCADE, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.title


class Order(models.Model):
    ref_code = models.CharField(max_length=15, null=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.SET(None))
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    # payment details = models.ForeignKey(Payment, null=True)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.price for item in self.items.all()])

    def __str__(self):
        return f'{self.owner} - {self.ref_code}'

cart/views.py
from django.shortcuts import render, redirect, reverse
from .models import OrderItem, Order
from shop.models import Product

import time, datetime
from users.models import CustomUser

from django.contrib import messages

# local
from .extras import generate_order_id


# Create your views here.
def get_user_pending_order(request):
    if request.user.is_authenticated:
        order = Order.objects.filter(owner=request.user, is_ordered=False)
        if order.exists():
            return order[0]
    else:
        return redirect('/accounts/login/')


def add_to_cart(request, id):
    if request.user.is_authenticated:
        # if logged in add to cart
        product = Product.objects.get(id=id)

        order_item, status = OrderItem.objects.get_or_create(product=product)
        print(order_item)
        user_order, status = Order.objects.get_or_create(owner=request.user)
        print(user_order.owner.username)
        user_order.items.add(order_item)
        user_order.save()
        print(user_order.get_cart_items())


        if status:
            # generate refcode
            user_order.ref_code = generate_order_id()
            user_order.save()



        messages.info(request, "item added to cart")
        return redirect(reverse('products:product_list'))


    else:
        messages.info(request, "You need to log in before you can do that! You are now being redirected! Please wait.")
        time.sleep(2)
        return redirect('/accounts/login/')


def delete_from_cart(request, id):
    item_to_delete = OrderItem.objects.filter(pk=id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, 'Item has been deleted')
    return redirect(reverse('shopping_cart:order_summary'))


def order_details(request, id):
    if request.user.is_authenticated:
        existing_order = get_user_pending_order(request)
        context = {
            'order': existing_order,
        }
        return render(request, 'cart/order_summary.html', context)
    else:
        messages.info(request, "You need to log in before you can do that! You are now being redirected! Please wait.")
        return redirect('/accounts/login/')


def checkout(request):
    if request.user.is_authenticated:
        existing_order = get_user_pending_order(request)
        context = {
            'order': existing_order,
        }
        return render(request, 'cart/checkout.html', context)
    else:
        messages.info(request, "You need to log in before you can do that! You are now being redirected! Please wait.")
        return redirect('/accounts/login/')


def process_payment(request, order_id):
    # process payment
    return redirect(reverse('shopping_cart:update_records'), kwargs={
        'order_id': order_id
    })


def update_transaction_records(request, order_id):
    # get the order being processed
    order_to_purchase = Order.objects.filter(pk=order_id).first()

    # update placed order
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()

    # get all items in the order
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Grab the user profile
    user_profile = CustomUser.objects.get(username=request.user.username)

    # get all the order items and add to the users purchased items
    order_products = [item.product for item in order_items]
    user_profile.purchased_items.add(*order_products)
    user_profile.save()

    """ 
    To do:
    1. Update payment records
    2. send email to customer confirming order
    3. send order details to site admin/ shipping to know an order needs to be shipped after payment received
    
    """
    messages.info(request, "Thankyou, your items have been added to your profile!")
    return redirect(reverse('users:my_profile'))


def success(request):
    pass

cart/templates/cart/checkout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
<table>
    <tr><td><h4>Order summary</h4></td></tr>
    <tr>
        <td>
        {% for item in order.get_cart_items %}
            <tr>
            <td>{{ item }}</td>
            <td>{{ item.product.price }}</td>
            </tr>
        {% endfor %}
        </td>
    </tr>
    <tr>
        <td>Order total:</td>
        <td>{{ order.get_cart_total }}</td>
    </tr>
</table>

<form method="post" action="{% url 'shopping_cart:process_payment' order.id %}">
    {% csrf_token %}
    <button>Pay with card</button>
</form>
{% endblock content %}

</body>
</html>

cart/templates/cart/order_summary.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
<table>
<tr>
    <th>Ref code</th>
    <th>Item</th>
    <th>Price</th>
</tr>
{% for item in order.get_cart_items %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>
            {{ item.product.title }}
            <a href="{% url 'shopping_cart:delete_item' item.id %}">Delete</a>
        </td>
        <td>{{ item.product.price }}</td>
    </tr>
{% empty %}
<tr>
    <td>You have not added any items yet.</td>
</tr>
{% endfor %}

<tr>
    {% if order.get_cart_total != None %}
    <td>Order total:</td>
    <td>{{ order.get_cart_total }}</td>
</tr>
{% endif %}

<tr>
    <td><a href="{% 'products:product_list' %}">
        {% if order %}Continue shopping{% else %}Add items to cart{% endif %}
    </a></td>
    <td>{% if order.get_cart_items %}
        <a href="{% url 'shopping_cart:checkout' %}">Proceed to checkout</a></td>
        {% endif %}
</tr>
</table>
{% endblock content %}

</body>
</html>

cart/templates/cart/payfast_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock content %}

</body>
</html>

cart/templates/cart/purchase_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}

{% endblock content %}

</body>
</html>