cart/urls.py
from django.urls import path

app_name = 'shopping_cart'

from.views import (
add_to_cart,
delete_from_cart,
order_details,
checkout,
process_payment,
update_transaction_records,
success,
)

urlpatterns = [
    path('add-to-cart/<int:id>/', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name="purchase_success"),
    path('item/delete/<int:id>/', delete_from_cart, name='delete_item'),
    path('checkout/', checkout, name="checkout"),
    path('payment/<int:order_id>/', process_payment, name="process_payment"),
    path('update-transaction/<int:order_id>/', update_transaction_records, name="update_records"),

]

lol_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views


urlpatterns = [
    path('admin/', admin.site.urls),

    # shop app
    path('', views.product_list_view, name='home_page'), # home page

    path('product/', include('shop.urls')),

    path('about/', views.about_view, name='about_view'),

    path('contact/', views.contact_view, name='contact_view'),

    # users app
    path('users/', include('users.urls')),
    path('accounts/', include('allauth.urls')),

    # cart app
    path('shopping-cart/', include('cart.urls')),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.product_list_view,  name='product_list'),
    path('<int:id>/', views.product_detail_view, name='product_detail_view'),
]

shop/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
"""
Category can be used to future use, for site with multiple types of items,
which would require a foreign key to be added to Product model.

class Category(models.Model):
    name = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
"""



class Product(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('title',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('products:product_detail_view', kwargs={'id': self.id})

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product


# Create your views here.


def product_list_view(request):
    # use this function for home page to display all available items

    products = Product.objects.filter(available=True)

    context = {
        'products': products

    }

    return render(request, 'base.html', context)


def product_detail_view(request, id):
    # this function is for individual item pages.
    try:
        product = Product.objects.get(id=id)
        context = {
            'product': product
        }
        return render(request, 'detail.html', context)
    except Product.DoesNotExist:
        return redirect('/')


def about_view(request):
    context = {}
    return render(request, 'about.html', context)


def contact_view(request):
    context = {}
    return render(request, 'contact.html', context)

shop/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
     {% extends 'base.html' %}
    {% load static %}

    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% include 'navbar.html' %}
</body>
</html>

shop/templates/base.html
<!DOCTYPE html>
<!-- This base.html is the home page of the website where all items will be listed.
detail.html is where each item will be displayed in more depth.
-->

<html lang="en">
<head>
    {% load static %}
    {% load socialaccount %}
    <meta charset="UTF-8">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block title %}League Posters{% endblock title %}</title>
</head>
<body>
{% include 'navbar.html' %}

{% block content %}

{% block all_products %}

  <h1>User is: {{ request.user }} - Logged in: {{ request.user.is_authenticated }}</h1>
<div class="container-products">
        {% for poster_item in products %}

            <div class="flex-poster-item">
                <a href="{{ poster_item.get_absolute_url }}">
                    <img src="#" style="margin:10px;width:240px; height:240px;">
                <h1>{{ poster_item.title }}</h1>
                <br>
                    <p>{{ poster_item.description }}</p>
                    <p>Price: £{{ poster_item.price }}</p>
                </a>
            </div>

        {% endfor %}
</div>
    {% endblock all_products %}

{% endblock content %}

{% block footer %}
<footer>

</footer>
{% endblock footer %}

</body>
</html>

shop/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}

    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

shop/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% extends 'base.html' %}
    {% load static %}

    <meta charset="UTF-8">
    <title>{% block title %}
        {{ product.title }} | LoL Posters
        {% endblock title %}</title>
</head>
<body>
{% block content %}
<div style="display:flex; justify-content: center; flex-direction: column;">
    <img src="#" style="margin:10px;width:240px; height:240px;">
    <h1>{{ product.title }}</h1>
    <br>
    <p>{% if product.stock == 0 %}
        <p>This product is currently being re-stocked! You can still order this item for delivery asap or contact us
to find out when we will have it!</p>
        {% endif %}
    <p>{{ product.description }}</p>
    <p>Price: £{{ product.price }}</p>

    <a href="{% url 'shopping_cart:add_to_cart' product.id %}">Add to cart</a>
    <a href="{% url 'shopping_cart:order_summary' %}">Go to cart</a>
</div>
{% endblock content %}
</body>
</html>

shop/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    {% load socialaccount %}

    <meta charset="UTF-8">
    <title></title>
</head>
<body>

{% block navbar %}

<nav>

    <div class="nav-container">


        <li><a href="/">Home</a></li>
        <li><a href="/">Products</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'account_logout' %}">Log Out</a></li>
            <li><a href="#">My Cart</a></li>
        {% else %}
            <li><a href="{% url 'account_login' %}">Log In</a></li>
            <li><a href="{% url 'account_signup' %}">Sign up</a></li>
            <li><a href="{% provider_login_url 'google' %}">Gmail Log In</a></li>
        {% endif %}
    </div>
</nav>
{% endblock navbar %}

</body>
</html>